import { Role } from '../types';

export enum Permission {
  // Admin & System
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_SYSTEM_SETTINGS = 'MANAGE_SYSTEM_SETTINGS',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
  
  // Coordinator
  MANAGE_BIOMASS_RECORDS = 'MANAGE_BIOMASS_RECORDS',
  ASSIST_DATA_ENTRY = 'ASSIST_DATA_ENTRY',
  MANAGE_HUB_INVENTORY = 'MANAGE_HUB_INVENTORY',
  CREATE_AGGREGATION_GROUP = 'CREATE_AGGREGATION_GROUP',
  MANAGE_LISTINGS = 'MANAGE_LISTINGS',
  RESPOND_TO_INQUIRIES = 'RESPOND_TO_INQUIRIES',
  
  // Buyer
  BROWSE_VALIDATED_LISTINGS = 'BROWSE_VALIDATED_LISTINGS',
  SUBMIT_INQUIRY = 'SUBMIT_INQUIRY',
  VIEW_OWN_INQUIRIES = 'VIEW_OWN_INQUIRIES',
  
  // LGU / Institutional
  VIEW_SYSTEM_WIDE_RECORDS = 'VIEW_SYSTEM_WIDE_RECORDS',
  VIEW_GIS_MAP = 'VIEW_GIS_MAP',
  GENERATE_REPORTS = 'GENERATE_REPORTS',
  VIEW_VALIDATION_QUEUE = 'VIEW_VALIDATION_QUEUE',
  VALIDATE_BIOMASS_RECORD = 'VALIDATE_BIOMASS_RECORD',
}

const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.ADMINISTRATOR]: [
    Permission.MANAGE_USERS,
    Permission.MANAGE_SYSTEM_SETTINGS,
    Permission.VIEW_AUDIT_LOGS,
    Permission.VIEW_SYSTEM_WIDE_RECORDS,
  ],
  [Role.COORDINATOR]: [
    Permission.MANAGE_BIOMASS_RECORDS,
    Permission.ASSIST_DATA_ENTRY,
    Permission.MANAGE_HUB_INVENTORY,
    Permission.CREATE_AGGREGATION_GROUP,
    Permission.MANAGE_LISTINGS,
    Permission.RESPOND_TO_INQUIRIES,
  ],
  [Role.BUYER]: [
    Permission.BROWSE_VALIDATED_LISTINGS,
    Permission.SUBMIT_INQUIRY,
    Permission.VIEW_OWN_INQUIRIES,
  ],
  [Role.LGU]: [
    Permission.VIEW_SYSTEM_WIDE_RECORDS,
    Permission.VIEW_GIS_MAP,
    Permission.GENERATE_REPORTS,
    Permission.VIEW_VALIDATION_QUEUE,
    Permission.VALIDATE_BIOMASS_RECORD,
  ],
};

export const hasPermission = (role: Role, permission: Permission): boolean => {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
};
